# Generated by Django 5.2.8 on 2025-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sizes_and_prices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('momos', 'Momos'), ('chilly', 'Chilly'), ('gravy', 'Gravy'), ('dry', 'Dry'), ('rolls', 'Rolls'), ('soup', 'Soup'), ('main_veg', 'Veg Main'), ('main_nonveg', 'Non-Veg Main')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('veg_starter', 'Veg Starter'), ('nonveg_starter', 'Non-Veg Starter'), ('chinese_veg', 'Chinese Veg'), ('chinese_nonveg', 'Chinese Non-Veg'), ('indian_main', 'Indian Main Course'), ('breads', 'Breads'), ('others', 'Others')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'time')},
        ),
    ]
