# Generated by Django 5.2.8 on 2025-11-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('chinese_veg_starter', 'Chinese Veg Starter'), ('chinese_nonveg_starter', 'Chinese Non-Veg Starter'), ('veg_indian_snacks', 'Veg Indian Snacks'), ('nonveg_indian_snacks', 'Non-Veg Indian Snacks'), ('soups', 'Soups'), ('snacks', 'Snacks'), ('mocktail', 'Mocktail'), ('chinese_veg_tandoori', 'Chinese Veg Tandoori Starter'), ('chinese_nonveg_tandoori', 'Chinese Non-Veg Tandoori Starter'), ('bombil_seafood', 'Bombil Sea Food'), ('quick_bites', 'Quick Bites'), ('chinese_veg_rice', 'Chinese Veg Rice'), ('chinese_veg_noodles', 'Chinese Veg Noodles'), ('chinese_nonveg_rice', 'Chinese Non-Veg Rice'), ('chinese_nonveg_noodles', 'Chinese Non-Veg Noodles'), ('veg_indian_main', 'Veg - Indian Main Course'), ('vegetable', 'Vegetable'), ('dum', 'Dum'), ('paneer', 'Paneer'), ('fish_tandoori', 'Fish Tandoori'), ('ginger', 'Ginger'), ('breads', 'Breads')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('momos', 'Momos'), ('chilly', 'Chilly'), ('manchurian', 'Manchurian'), ('dry', 'Dry'), ('gravy', 'Gravy'), ('rolls', 'Rolls'), ('chinese_soup', 'Chinese Soup'), ('hot_sour_soup', 'Hot and Sour Soup'), ('clear_soup', 'Clear Soup'), ('steam', 'Steam'), ('fry', 'Fry'), ('paneer_tikka', 'Paneer Tikka'), ('chicken_tikka', 'Chicken Tikka'), ('tandoori', 'Tandoori'), ('fried_rice', 'Fried Rice'), ('schezwan_rice', 'Schezwan Rice'), ('triple_schezwan', 'Triple Schezwan'), ('manchurian_rice', 'Manchurian Rice'), ('burnt_garlic', 'Burnt Garlic'), ('hakka_noodles', 'Hakka Noodles'), ('schezwan_noodles', 'Schezwan Noodles'), ('triple_schezwan_noodles', 'Triple Schezwan Noodles'), ('manchurian_noodles', 'Manchurian Noodles'), ('cheese_noodles', 'Cheese Noodles'), ('dal', 'Dal'), ('masala', 'Masala'), ('curry', 'Curry'), ('paneer_dishes', 'Paneer Dishes'), ('egg', 'Egg'), ('chicken', 'Chicken'), ('mutton', 'Mutton'), ('prawns', 'Prawns')], max_length=50, null=True),
        ),
    ]
